### ISSUE TITLE
Provide window-stack component set as a dedicated npm package

### ISSUE THREAD

**Issue by gurkerl83** [tvillarete/ipod-classic-js#1]
Hi, this is not an issue but rather a question about the window-stack component implemented in your application. In my application, I have a similar need to organize several views and make the transition through a modern animation library happen. Are there any plans to extract this fundamental component set from the iPod-classic application and provide it through a dedicated npm package?  Thx

**Comment by tvillarete** [comment]
Hi! Apologies for the almost 1.5yr late response 😅 

I currently have no plans on supporting a dedicated npm package for this, though I do agree it'd be a very useful tool for many projects. Thanks for suggesting!
