### ISSUE TITLE
Login isn't working again

### ISSUE THREAD

**Issue by Mattis142** [tvillarete/ipod-classic-js#103]
Unfortunately logging in with both Spotify or apple music isn't working again, apple music returns a "Problem connecting" error and Spotify returns me back to the ipod interface, nothing changes tho

**Comment by joshistoast** [comment]
Same here

**Comment by tvillarete** [comment]
Figured out the issue and wrote up an explanation on the root cause in this thread: https://github.com/tvillarete/ipod-classic-js/issues/107#issuecomment-1183993762

Thanks!
