### ISSUE TITLE
Login isn’t working

### ISSUE THREAD

**Issue by InfxniteWrlds** [tvillarete/ipod-classic-js#107]
Can’t log into Apple Music, I could log into Spotify, however, but needed a premium account.

**Comment by Akira-25** [comment]
me too. iPhone XS iOS15.5   really want to use this

**Comment by tvillarete** [comment]
Apologies for the delay here – I believe I was able to figure out the issue (related to the error `ERROR_FAILED_TO_VERIFY_JWT` for anyone google searching this error code in the future). 

After doing some digging, I figured out that my previous MusicKit API key had exceeded its request quota, so I set up a new one and was able to log in properly.

Let me know if you still can't log into Apple Music and I can do some more digging; closing this ticket now though. Thanks for flagging!

**Comment by Akira-25** [comment]
> Apologies for the delay here – I believe I was able to figure out the issue (related to the error `ERROR_FAILED_TO_VERIFY_JWT` for anyone google searching this error code in the future).
> 
> After doing some digging, I figured out that my previous MusicKit API key had exceeded its request quota, so I set up a new one and was able to log in properly.
> 
> Let me know if you still can't log into Apple Music and I can do some more digging; closing this ticket now though. Thanks for flagging!

Thank you so much!! It works perfect and I'm so happy!!
