### ISSUE TITLE
Soundcloud compatibility

### ISSUE THREAD

**Issue by YuaBeVibin** [tvillarete/ipod-classic-js#109]
Will this ever get Soundcloud as a sign in option? Both Apple Music and Spotify has to have some sort of paywall to be used on this, thus I rarely use Spotify either way.

**Comment by tvillarete** [comment]
Hey @YuaBeVibin, thanks for the suggestion! While I'd love to have been able to explore this as a sign-in option, it unfortunately looks like SoundCloud no longer allows developers to access user account data (liked tracks, playlists, etc). According to [this thread](https://stackoverflow.com/questions/54753238/soundcloud-application-registration-form-is-closed), it's been this way for nearly 4 years, so it's highly unlikely that this will ever change 🤷 

<img width="638" alt="Screen Shot 2022-07-08 at 11 43 05 AM" src="https://user-images.githubusercontent.com/21055469/178051921-1f8a777d-762a-489b-b3e2-6f51c02a536f.png">
