### ISSUE TITLE
No longer Apple Music option?

### ISSUE THREAD

**Issue by Mflynn11** [tvillarete/ipod-classic-js#131]
When signing in the Apple Music option is gone?

**Comment by tvillarete** [comment]
Hey @Mflynn11, thanks for flagging! Unfortunately Apple's developer tokens expire every 6 months without warning, and that's what happened here. I've updated the token, so if you refresh your web page the Apple Music option should be present again. Let me know if it still isn't showing up for you. 

Thanks!

**Comment by Mflynn11** [comment]
Thanks for the quick reply! Option has returned but after signing in I now get “problem connecting”
