### ISSUE TITLE
Token expired

### ISSUE THREAD

**Issue by grantwinnberg** [tvillarete/ipod-classic-js#132]
Every time I try to sign in w/ Spotify, I get this error

"Jwks remote fetch is failed"

**Comment by tvillarete** [comment]
Hey @grantwinnberg, thanks for flagging. It looks like all of Spotify is experiencing issues right now, which also affects this app. Their twitter has some updates about it:

https://twitter.com/SpotifyStatus/status/1614078310023045129?s=20

**Comment by tvillarete** [comment]
Looks like things are back to normal now, so I'm going to close this issue 👍
