### ISSUE TITLE
Deezer

### ISSUE THREAD

**Issue by tarikalmashni** [tvillarete/ipod-classic-js#138]
Looks great but I can't test it. Please add either Deezer support or Spotify free account support (probably not doable with their API?)

**Comment by tvillarete** [comment]
Hey @tarikalmashni, thanks for the request!

Unfortunately I have no plans to add support for Deezer or any other streaming service. This project was more of a fun hobby and is not actively being developed except for when I have inspiration or motivation to add new features. 

This is an open source project though, so if you're curious and have some free time, I highly recommend digging into the Deezer API to see if it's something that you could build out yourself! I'm always happy to review pull requests or answer implementation questions, so let me know if there's anything about my project's architecture that I can help you with if you do choose to try and implement this yourself.

Best of luck!
