### ISSUE TITLE
Adding and storing local music files through LocalForage?

### ISSUE THREAD

**Issue by HunterBoy344** [tvillarete/ipod-classic-js#142]
Music streaming is great for some, but not for people like me; I like to own and have direct access to my music, which is why I like the iPod in the first place.

Would it be possible to add loading local files to iPod.js? In theory, LocalForage could be used to store the user’s music files in PWA local storage so they can be loaded with the iPod.js UI and not the iOS file menu. File size would probably have to be limited due to local storage limits, but even having some ability to add, store, and play local music files would absolutely make my day.

**Comment by HunterBoy344** [comment]
I might actually just do this myself. Doesn’t seem exceptionally difficult since the code here is well organized. I’ll update if I manage to do it.

**Comment by HunterBoy344** [comment]
Oh heck no this project’s code is spaghetti to me, I can’t make heads or tails of it.

**Comment by mankybansal** [comment]
@HunterBoy344 lmao that was a good 6hrs 😂

**Comment by HunterBoy344** [comment]
I have good news; while I couldn’t get local files to work, I was able to make iCloud Music Library work! This basically has the same effect; any files you add to iTunes will work on iPod.js, regardless of whether or not they’re in the iTunes Store or Apple Music.
