### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by ShyrimAiko** [tvillarete/ipod-classic-js#143]
spotify is no longer working as it should, many times it works normally, however, lately it does not connect and now an error screen is appearing for me
![Screenshot_20230412-200251_Chrome](https://user-images.githubusercontent.com/130614163/231604858-bc616c01-4d34-4634-b93b-ceec778ec849.jpg)

**Comment by tvillarete** [comment]
Hey! Apologies, the power went out and my auth server reset. It should be back up and running. 

My hope is to set up a more robust authentication system soon using Vercel as the host, but I haven't had much time these days. 

Feel free to let me know if you still can't log in. Thanks for flagging!

**Comment by ShyrimAiko** [comment]
No problem, I understand perfectly, however I'm still having trouble
logging in :(

sorry if my english is not good, i'm brazilian🇧🇷

Em qui., 13 de abr. de 2023 2:30 AM, Tanner Villarete <
***@***.***> escreveu:

**Comment by tvillarete** [comment]
Ah I see. Can you elaborate on the error you are seeing when trying to log in? Is it still the same Ngrok issue?
