### ISSUE TITLE
Spotify login not working

### ISSUE THREAD

**Issue by Grafaffel** [tvillarete/ipod-classic-js#150]
Logging in with Spotify gives you an error from ngrok.

**Comment by tvillarete** [comment]
Hey @Grafaffel, thanks for the heads up — I've known about this for a little over a week and have been working on a solution that should resolve this error permanently.

I've been working on [migrating the entire app to Next.js](https://github.com/tvillarete/ipod-classic-js/compare/tvillarete/next-js-migration?expand=1) which has allowed me to move off of my own authentication server and onto [Vercel](https://vercel.com/).

The good news is that migration is (mostly) complete and should be live as of an hour ago. Feel free to give it a try! You ideally won't see any differences besides Spotify and Apple Music working correctly.

I will be updating this repo's documentation and fixing some style issues in the next few days, but in the meantime I'm going to mark this issue as resolved 👍 Let me know if you run into any other issues, and thanks again!
