### ISSUE TITLE
Apple Music option no longer appears

### ISSUE THREAD

**Issue by jamiw1** [tvillarete/ipod-classic-js#165]
Title. Currently unable to sign into Apple Music, as the option doesn’t appear in neither sign in menu, with Spotify being the only option.

**Comment by tvillarete** [comment]
👋 Thanks for the report. Apple developer tokens expire every 180 days and I'm required to manually refresh it. Give it another try and it should work

**Comment by jamiw1** [comment]
Thank you! It works now
