### ISSUE TITLE
Spotify: Show popup when non-premium user signs in

### ISSUE THREAD

**Issue by fireattack** [tvillarete/ipod-classic-js#31]
Copied from https://news.ycombinator.com/item?id=27606099
	
>neogodless 5 hours ago [–]
    
    Firefox on Windows 10 with uBlock Origin (which I disabled on this page) and Multi-Account Containers. I'm not a Spotify paid user, and the error I get is different:
    > Cannot register to Track Playback with non-premium user.
    
    However, the "iPod" just keeps telling the user to sign in. It might be good to have some indicator that you need a paid account to use Spotify on this iPod.

>neogodless 4 hours ago [–] 
    
    Do you have a free account? I had to pop open Developer Tools to see that there's an error if you don't have a paid account that prevents the iPod.js from connecting to your account.

Probably should add some warnings if that happens, instead of failing silently.

**Comment by tvillarete** [comment]
Hey @fireattack, thanks for noting this! It hadn't occurred to me to test this on a non-premium account as I've had premium for years 😅 I can definitely add a popup that warns the user that it only works with a premium account. 

Spotify's SDK might have a way to play previews, though I'd have to do a bit of digging. Thanks again!

**Comment by tvillarete** [comment]
Fixed by https://github.com/tvillarete/ipod-classic-js/pull/56. Closing this issue now 👍

**Comment by Wynadorn** [comment]
The popup didn't show when I tried it on android in Chrome. Was wondering why it didn't work for me until I found this issue.
