### ISSUE TITLE
Spotify & Apple Music: Add pagination to API responses

### ISSUE THREAD

**Issue by ronaldlangeveld** [tvillarete/ipod-classic-js#34]
Noticed a bug where whilst using Apple Music it only loads the first set of Albums and Artists, instead of loading the next set / "page" once scrolled to the bottom of the list. 

Perhaps due to Apple's API limits? or a bug?

**Comment by tvillarete** [comment]
Hey @ronaldlangeveld, this one's on my radar. Not a limitation of Apple's API; I need to set up a pagination system that triggers the next set of songs to load when we've scrolled to the bottom of the list. Thanks for noting!

**Comment by ronaldlangeveld** [comment]
Awesome thanks!
Great project!

**Comment by tvillarete** [comment]
Tying https://github.com/tvillarete/ipod-classic-js/issues/48 into this issue since they're both closely related. I have a branch in the works that adds pagination for both Spotify and Apple Music when scrolling to the bottom of the list of albums/artists/songs/etc
