### ISSUE TITLE
U2 iPod

### ISSUE THREAD

**Issue by getaaron** [tvillarete/ipod-classic-js#36]
As a user I should be able to change the iPod to the U2 iPod in settings. 

![](https://www.imore.com/sites/imore.com/files/styles/larger/public/field/image/2016/05/U2-iPod.jpg?itok=lnFmd8hQ)

**Comment by Foxlum** [comment]
@getaaron I'd recommend this expand into something like (Custom iPod Colors), though color variants were rarely made in the classic line, they did go all out on the mini, nano, and Shuffle.

**Comment by tvillarete** [comment]
Love this idea! I do have a branch open that adds theming to the shell and scroll wheel, so adding a U2 variant wouldn't be too much extra work and would be quite a fun easter egg. I'll keep this in mind if I have some extra time 😄

**Comment by mankybansal** [comment]
@getaaron @Foxlum what do you think? PR: https://github.com/tvillarete/ipod-classic-js/pull/40

**Comment by getaaron** [comment]
Looks incredible!
