### ISSUE TITLE
iOS HomeScreen Bookmark: Support background play

### ISSUE THREAD

**Issue by cyriac** [tvillarete/ipod-classic-js#38]
Opening the app on Chrome or Safari on iPhone, and switching apps continues to play the song in the background, including the locked screen state.

But once you add it to the Home screen via - Safari > Share icon > Add to Home Screen. The "app" added to the home screen does not play songs in the background, stops immediately when you switch the app or the screen locks.

**Comment by crutchcorn** [comment]
Seems like this is a limitation of iOS:

https://blog.prototyp.digital/what-we-learned-about-pwas-and-audio-playback/

Maybe we could wrap inside of Cordova and make a publish-able iOS app?

https://thecodebeast.com/post/cordova-allow-audio-to-play-in-background-and-in-silent-switch/72

Maybe even using Airport to sidestep some of the Apple publishing rules?

https://airport.community/

**Comment by tvillarete** [comment]
Hey @cyriac, I was actually chatting with a Spotify dev and they mentioned this as one of the current roadblocks for iOS browser support they've run into. It is indeed a limitation of iOS Home Screen bookmarks, and from what I heard they _want_ to support it but are limited by Apple unfortunately.

**Comment by tvillarete** [comment]
> Maybe we could wrap inside of Cordova and make a publish-able iOS app?

This sounds like a repeat of history in the making 😅 There was an app called [Rewound](https://www.theverge.com/2019/12/16/21024729/apple-rewound-app-iphone-ipod-click-wheel-web-android-not-available) that got pulled from the App Store that was accomplishing something similar. 

> Maybe even using Airport to sidestep some of the Apple publishing rules?

Interesting! I'm not really sure how iOS WebView would handle Spotify or even Apple's SDKs, but might be worth a shot 🤷

**Comment by tvillarete** [comment]
Going to close this issue as there aren't many actionable items in the scope of this web project. I definitely appreciate the suggestions though!
