### ISSUE TITLE
Missing Apple developer token

### ISSUE THREAD

**Issue by ritchxu** [tvillarete/ipod-classic-js#39]
Running `yarn start` on Mac in Microsoft Edge browser (same in Safari) and got the error page of `Missing Apple developer token`. Could be something silly I missed, but wanna ask to increase visibility. 😁

**Comment by tvillarete** [comment]
Hey @ritchxu, thanks for pointing this out. I hadn't made it clear in the README that an Apple Dev Token is required to run the app locally. You can add one via the `token` query param like so:

`https://localhost:3000?token=<APPLE_DEV_TOKEN>`

Perhaps I can figure out a way for it to not be required by default to run, but there's a lot of code connected directly to MusicKit JS and it'll error out in multiple places if we don't supply the token. Hope that helps! I also update the readme here: https://github.com/tvillarete/ipod-classic-js/pull/41

**Comment by ritchxu** [comment]
Thanks @tvillarete that would be a great addition, since the app requires enrolling Apple Developer Program as it stands now, which costs $99/year if I understand it right?

**Comment by tvillarete** [comment]
> Which costs $99/year if I understand it right?

That is correct. I also wasn't too thrilled when I found out about that, given that this is a free and open source project unlike an app published on the app store. I'd love to be able to give out dev tokens freely, but I have to be careful given that it's associated with my Apple ID. 

If you plan on developing on this project, send me an email (tvillarete@gmail.com) with your pushed branch name and a bit of details on what you want to build or have built and I'd be happy to send you a dev token. Thanks!
