### ISSUE TITLE
iPod socks

### ISSUE THREAD

**Issue by getaaron** [tvillarete/ipod-classic-js#43]
As a user I want to put my iPod in an iPod sock to protect it

![iPod socks](https://media.guitarcenter.com/is/image/MMGS7/iPod-Socks-Set-of-Six-Knit-Socks/410710000000000-00-2000x2000.jpg)

![two iPods in socks](https://static.toiimg.com/photo/55162641.cms?imglength=50294)

**Comment by getaaron** [comment]
iPod socks come in one color for each day of the week, and gray for the weekend

**Comment by tvillarete** [comment]
I love to think that Apple had some user stories just like this when they made those socks 😅

I don't plan on building this, but if anyone else wants to take a stab at it, feel free lol
