### ISSUE TITLE
Spotify: Spotify only loads 100 random artists

### ISSUE THREAD

**Issue by guurila** [tvillarete/ipod-classic-js#48]
Spotify has the same issue as apple for loading artists. About 100 artist in random order.

**Comment by tvillarete** [comment]
Hey @guurila, thanks for filing this! I have a branch in the works that adds pagination for both Spotify and Apple Music when scrolling to the bottom of the list of albums/artists/songs/etc. I'm gonna combine this ticket with another that's already open (https://github.com/tvillarete/ipod-classic-js/issues/34) and close out this one

**Comment by guurila** [comment]
Excellent and thank you very much for working on this. I've been looking
for a player to use with Spotify to make it about music I want.
