### ISSUE TITLE
Allow use of local music files instead of cloud based services 

### ISSUE THREAD

**Issue by Foxlum** [tvillarete/ipod-classic-js#57]
Instead of using Spotify or Apple Music, allow for the ability to use local files such as .mp3, .m4a, .flac, and .wav's.

**Comment by tvillarete** [comment]
Hey @Foxlum, this would be a neat addition. Unfortunately this probably won't ever be implemented (by me at least) for a few reasons:

1. Most of the code relies on a whole lot of metadata that is required to display things properly. Think Album info, artwork, song names, etc. that is not guaranteed to be present in an uploaded file.
2. Uploaded files would need to have a rigid directory structure to function. For example, `Artists > Coldplay > Parachutes > Don't Panic` would require a very specific file structure and would require quite a bit of data manipulation on the user's part.
3. This is just simply a _lot_ of work for not much gain as most users tend to have either a Spotify or Apple Music account.

I appreciate the suggestion, and definitely give it a try if you're inclined! But I'm gonna close this ticket. Thanks!
