### ISSUE TITLE
[New UI]: Support Repeat & Shuffle

### ISSUE THREAD

**Issue by immadolf** [tvillarete/ipod-classic-js#62]
Hello, I like this app very much, but I have a problem in using it, I want to set a song single loop, but I have searched all over the settings but I can't find this option, could you please help me?

**Comment by tvillarete** [comment]
Hey @immadolf, thanks for bringing this up! At the moment there is no way to toggle repeat/shuffle/etc, but this is something I'd like to implement. I'm going to turn this issue into a feature request and will look into implementing it in the near future 👍

**Comment by immadolf** [comment]
Thank you, you are so generous
