### ISSUE TITLE
Music pauses when back to home screen

### ISSUE THREAD

**Issue by Flankstangh** [tvillarete/ipod-classic-js#63]
I really appreciate this project, but I also encountered a perplexity while using, don't know if it's a bug or "special feature" of Safari:

The player actually works well when entering the page directly through Safari search bar, exiting Safari does not disturb background playing.

But if I add the website to home screen, and enter the page via home screen icon, then any attempt to leave the website will pause the music（such as swiping up to home screen, shifting to other apps or just turning off the phone screen).

My iOS version is 14.6.

**Comment by tvillarete** [comment]
Hey @Flankstangh, unfortunately this is a known limitation with iOS Safari home screen bookmarks, and there is no indication from Apple that it will ever be fixed. Feel free to check out a previous discussion here: https://github.com/tvillarete/ipod-classic-js/issues/38

Wish I could say this was something I could fix, but the best we can hope for is that Apple gets around to revamping Homescreen bookmarks one day 🤷
