### ISSUE TITLE
Failed to complete funnel connection error on iPhone 

### ISSUE THREAD

**Issue by 90sFavKi** [tvillarete/ipod-classic-js#66]
Hello was trying to sign in using Spotify and I got the failed to complete tunnel connection error I have attached the picture below, hopefully this can be fixed I would really like to use it 
![8459B070-69FC-4291-864F-C77F735CAA1E](https://user-images.githubusercontent.com/67302463/128619866-4c6c7f7f-7bcb-4ea3-ae77-eab8ee599024.jpeg)

**Comment by tvillarete** [comment]
Hey @90sFavKi, thanks for pointing this out! Looks like the server that authenticates for Spotify errored out. I restarted it and looks like things are back up. Give it a try and let me know if you're still having issues. Closing this for now 👍
