### ISSUE TITLE
How to run this in VS code?

### ISSUE THREAD

**Issue by Sagaljyotsingh** [tvillarete/ipod-classic-js#68]

**Comment by tvillarete** [comment]
Hi @Sagaljyotsingh, 

Viewing code in VSCode is similar to opening up a Word document. Just open the directory and you can explore & edit the contents inside.

If you are trying to run the code locally in a browser, you will need to open up a terminal and follow the directions in my [README](https://github.com/tvillarete/ipod-classic-js#running-locally) to get set up properly.
