### ISSUE TITLE
Can't sign in spotify

### ISSUE THREAD

**Issue by Utsav-Murudi** [tvillarete/ipod-classic-js#91]
I ran it locally and after trying to sign in spotify, the link in the address changes from `http://localhost:3000/` to `http://localhost:3000/?code=AQA4XjhJvIpgnLYBLK2Z6mtYqp00vBY82wP0I1kVJZ5riZe5Neb55EA80vIsXqU6xDRWz60kfyu1YI1NWJCvjjd8rejBO4wsvC6xgbBXSmQ7Oz_4_9wJodKBFdgwVioaSXmeIYn9zVFPzLHQ5u40DusjBmhtDCuvcYeRCpEbJZiDC7IgEYAOSnh-eu0dFBuySeCg5tPF3FDJYps54iz-WSBcezaO3PRJlNJidIdjouGvZGH4zmc4I4WLhjWxqN_hcg4DIa1wB2NlhGmP8Jn6QhHHgDPiyN7aMKbLhIrvoq520gqssMKcOnKK78ENe2aa1maPnC6ATMXLsDXAnxH97CaGl31hU3yjvCkTaAZ6fv8i2sL4ExKzeEecJXXQnT1KWu1nE_k07betBNsWSWJAjjOysP5ZykTJCCEFzo8tYRs2kccG0Ky6SxzxDV0dWtp-an9VbA&state=UXwYRpN9I49zLl1n` and nothing happens. It does not login or even give an error. 

What am I supposed to do? Plus if I try the app from your website the same thing happens and link that appears in address bar is `https://tannerv.com/ipod/?code=AQCYpEYUEt-Sllde-79ixEuxsyE3EuNPJ7ygZXQSSQq6CqCN3HFY6XOcL50qmd33iYkHxmX_Axg0n-CRtu0q-1-UesHGZdKAYxgTfmMpElT2kzUQT3DKYBKJKfjbTm0lX5k5Bcyu0cv4MPmon9wbSV5g7KWR8Xj6KQNL0YLl6-RK1ctQXdjcUiBAIo9Ubni2AWnG1gCIungTR6h6TmDc-M_vpayXJ7FDe1xT3if4w6TQzCaIaBxapuecO0iIt_dhqwQBYKajBOP97GscR9wgBoKEtJzZAtKHRRvXmpL8mOcoHnJw3wIS1Xgv704oHRZ98QtcP_SFXwMIJigFLuXnmUYNFSxqzD6caIioAI8Wk_nt8QWw0ZLLsHr9o6hyNoibo3rBWhB59lSuHNCE1pkAojoGT_hNyukIFLuR-jku689Yt2FkKzx0KEGPsjeoim9mwjBBcHyhvA&state=pZemOY0Hy4xFFkgW`

**Comment by minefox199** [comment]
did a code got deleted or is not responding to Spotify servers?

**Comment by tvillarete** [comment]
Hey @Utsav-Murudi, apologies for the late response on this. If you're still interested in getting this to work, please send me the name of the browser you used. Sometimes different browsers (especially Safari) have issues connecting with Spotify's API. 

I tested signing on my own machine and things seem to be working, so let me know. Thanks!
