### ISSUE TITLE
Problem with sign in , wanted to make offline app for android

### ISSUE THREAD

**Issue by ghost** [tvillarete/ipod-classic-js#94]
hi sir i am very happy with your work but i can't sign in to that web app because i dont have apple music account and i can not sign in with spotify account so i want you for android make the app so that i can easily offline listen my songs stored in my phone

**Comment by tvillarete** [comment]
Hey @MyNameIsAnujRanjan,

Thanks for the suggestion! Unfortunately Apple Music and Spotify's web SDKs do not work with native Android, so you most likely won't be able to accomplish what you're asking for. Moreover, Apple Music and Spotify web SDKs require an internet connection to function properly, so even if it did run on Android, you'd still run into the offline issue.

Going to close this 👍
