### ISSUE TITLE
Cannot sign in to Apple Music

### ISSUE THREAD

**Issue by akidinatophat** [tvillarete/ipod-classic-js#96]
![image](https://user-images.githubusercontent.com/62395331/162729242-6c900ad4-34ee-4c5f-be43-761e173f0af7.png)

Keeps appearing even on different network.

**Comment by akidinatophat** [comment]
I don't know if this is just Apple's Oauth2 dying or not because normal Apple music works fine.

**Comment by JKakaofanatiker** [comment]
Same problem for me

**Comment by Bermudagirl52** [comment]
Same problem for me on iPhone 11, iPod Touch (7th gen) and Windows Laptop  (Chrome).

**Comment by tvillarete** [comment]
Should be fixed now 👍 

https://github.com/tvillarete/ipod-classic-js/issues/107#issuecomment-1183993762
