### ISSUE TITLE
Login issues 

### ISSUE THREAD

**Issue by dropstepp** [tvillarete/ipod-classic-js#97]
Will not work for sign in. 
tried Apple Music on safari. Says problem connecting and invalid oauth token 
![466B3512-0CD5-41B5-A445-3F1822D3EEF3](https://user-images.githubusercontent.com/104267729/164912659-ef61e278-4191-4256-8477-bb0c4a7e8a1e.png)
![C747C481-3CAD-4EA5-8DEC-F0BA8A2EB232](https://user-images.githubusercontent.com/104267729/164912662-98db930c-fcac-4227-b5ba-50151e8851b9.png)

**Comment by tvillarete** [comment]
Figured out the root cause. Thanks for flagging!

More info here: https://github.com/tvillarete/ipod-classic-js/issues/107#issuecomment-1183993762
