### ISSUE TITLE
Spotify sign in page is not working

### ISSUE THREAD

**Issue by ghost** [tvillarete/ipod-classic-js#99]
![Screenshot 2022-05-03 8 57 35 PM](https://user-images.githubusercontent.com/104833024/166441601-e000df04-6f73-4ccc-b073-3d42379b9719.png)

**Comment by ghost** [comment]
i press spotify sign in and it  errors

**Comment by tvillarete** [comment]
Hey @DizzyDog21, thanks for surfacing this. Ngrok is the utility I use to expose my Spotify authentication server via HTTPS, and apparently they changed the URL on me unexpectedly. I generated a new url and things should be working properly.

Unfortunately this may occur again unless I purchase a premium Ngrok license, so I'll set up an alert in case this happens again
